// Generated by: main
// TypeWriter: criteria
// Directive: +gen on byBlue

package sorting

func (p byBlue) Len() int      { return len(p) }
func (p byBlue) Swap(i, j int) { p[i], p[j] = p[j], p[i] }
