// Generated by: main
// TypeWriter: criteria
// Directive: +gen on byGreen

package sorting

func (p byGreen) Len() int      { return len(p) }
func (p byGreen) Swap(i, j int) { p[i], p[j] = p[j], p[i] }
