// Generated by: main
// TypeWriter: criteria
// Directive: +gen on byGrayscale

package sorting

func (p byGrayscale) Len() int      { return len(p) }
func (p byGrayscale) Swap(i, j int) { p[i], p[j] = p[j], p[i] }
